// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xezsussfapbkvfvpvzwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlenN1c3NmYXBia3ZmdnB2endtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODczMzAsImV4cCI6MjA2ODA2MzMzMH0.Jd-6KeE0DcZ-aWYd1Lbdbe_JGCoiJ6xYIiasTIppjUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});